[build]
  command = "npm run build"
  publish = ".next"
  environment = { NODE_VERSION = "20", NEXT_TELEMETRY_DISABLED = "1", ESLINT_IGNORE_DURING_BUILD = "true", TSC_COMPILE_ON_ERROR = "true" }

[[plugins]]
  package = "@netlify/plugin-nextjs"
